### ISSUE TITLE
metaissue: roadmap for mason registration

### ISSUE THREAD

**Issue by lucaferranti** [lucaferranti/ForwardModeAD#1]
#### Arithmetic functions

- [x] **(dual, dual)
- [x] **(real, dual)
- [x] sqrt
- [x] cbrt

#### Trigonometric

- [x] asin
- [x] acos
- [x] atan

#### Transcendental

- [x] exp2
- [x] expm1
- [x] log2
- [x] log10
- [x] log1p

#### Hyperbolic

- [x] sinh
- [x] cosh
- [x] tanh
- [x] asinh
- [x] acosh
- [x] atanh

### Derivatives

- [x] derivative
- [x] gradient
- [x] jacobian

### Tests

- [x] basic tests for functions

### Docs

- [x] basic chpldoc setup

### Extra

- [x] CI with github actions

**Comment by lucaferranti** [comment]
https://github.com/chapel-lang/mason-registry/pull/61
